using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    /// <summary>
    /// The initial migration accidentally marked <c>telegram_user_id</c> as a
    /// Postgres IDENTITY column. EF therefore treated the PK as DB-generated and
    /// quietly replaced the real Telegram user id with sequence values (1, 2, 3…),
    /// so on the next startup the session row could no longer be found and the
    /// user was prompted to log in again. This migration:
    ///   - Drops the identity from the column.
    ///   - Re-stamps existing rows so they hold the correct Telegram user id
    ///     (only safe to do automatically when there's at most one row and the
    ///     correct id is known via a manual UPDATE before deploying — otherwise
    ///     you should clear the table).
    /// Effective behaviour for fresh installs is: no identity, ids come from us.
    /// </summary>
    public partial class DropUserSessionIdentity : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                "ALTER TABLE user_sessions ALTER COLUMN telegram_user_id DROP IDENTITY IF EXISTS;");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                "ALTER TABLE user_sessions ALTER COLUMN telegram_user_id ADD GENERATED BY DEFAULT AS IDENTITY;");
        }
    }
}
